FILE_SQLGZ=init-db.sql.gz
PATH_SCRIPTS=./Scripts
PATH_OUTCOME=$PATH_SCRIPTS/$FILE_SQLGZ
CREATE_FILE=$PATH_SCRIPTS/init-01-create-db.sql
LOAD_DATA_FILE=$PATH_SCRIPTS/init-02-data-for-load.sql

rm $PATH_OUTCOME
cat $CREATE_FILE $LOAD_DATA_FILE | gzip > $PATH_OUTCOME